import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="max-w-[65ch] mx-auto"
    >
      <nav className="flex items-center gap-x-6 mb-8 p-4">
        <Link href={`/`}>Home</Link>
        <Link href={`/posts`}>Posts</Link>
      </nav>
      <div className="p-4">{children}</div>
    </div>
  );
}
